controller_list:
  - name: fake_summit_controller
    type: $(arg fake_execution_type)
    joints:
      - joint0
      - joint1
      - joint2
      - joint3
      - joint4
      - end_effector_joint
  - name: fake_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - end_effector_joint
initial:  # Define initial robot poses per group
#  - group: summit
#    pose: home

  []