controller_list:
  - name: arm_position_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - joint0
      - joint1
      - joint2
      - joint3
      - joint4
      - end_effector_joint